set -g mode-keys vi
set -g status-keys vi

#Make Space as the Leader key
unbind C-Space
set -g prefix C-Space
bind C-Space send-prefix

# Use | and - to split a window vertically and horizontally instead of " and % respoectively
unbind '"'
unbind %
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Cycle through windows using > and <
bind -r "<" swap-window -d -t -1
bind -r ">" swap-window -d -t +1

# Automatically set window title
set-window-option -g automatic-rename on
set-option -g set-titles on

# Move around panes with hjkl, as one would in vim after pressing ctrl + w
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

 ## Refresh status line every 5 seconds - Good for when music is playing / update time etc
#set -g status-interval 5

# Use 256 colors
set -g default-terminal "screen-256color"

# Status bar refresh interval
set -g status-interval 2

# Status bar style
set -g status on
set -g status-justify centre
set -g status-bg colour234
set -g status-fg colour223

# Left: Session name and hostname
set -g status-left-length 20
set -g status-left "#[fg=colour106,bold]#S"


# set -g @battery_percentage_script '~/.tmux/plugins/tmux-battery/scripts/battery_percentage.sh'
# set -g @battery_status_script '~/.tmux/plugins/tmux-battery/scripts/battery_status.sh'

# Right: Time, date, Battery, CPU Usage
set -g status-right-length 80
set -g status-right "#[fg=colour246]| %d-%b-%Y %H:%M %a"
# set -g status-right "#[fg=colour246]| CPU: #(ps -A -o %cpu | awk '{s+=$1} END {printf \"%.1f\", s}')% | Mem: #(vm_stat | awk '/Pages (free|active|inactive|wired):/ {total+=$2} END {printf \"%.0fMB\", total*4096/1048576}') | Batt: #($(@battery_percentage_script)) #($(@battery_status_script)) | %Y-%m-%d %H:%M"

# Active window
setw -g window-status-current-format "#[bg=colour172,fg=colour234,bold] #I:#W #[default]"

# Inactive windows
setw -g window-status-format "#[fg=colour246] #I:#W "

# Pane borders (optional)
set -g pane-border-style fg=colour238
set -g pane-active-border-style fg=colour172

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
# set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-cowboy'

# note: this line should always be the last
run '~/.tmux/plugins/tpm/tpm'
