COMPETITOR_SESSION="competitor"
COMPETITOR_EDITOR="editor"
COMPETITOR_INPUT="input"
COMPETITOR_RUNNER="runner"
COMPETITOR_WORKING_DIRECTORY="~/Legacy/Programming/C++/"

tmux has-session -t $COMPETITOR_SESSION 2>/dev/null
if [ $? != 0 ]; then
	tmux new -d -s $COMPETITOR_SESSION -n $COMPETITOR_EDITOR
	tmux send -t $COMPETITOR_SESSION:$COMPETITOR_EDITOR "cd $COMPETITOR_WORKING_DIRECTORY;vim 1test.cpp" Enter

	tmux new-window -t $COMPETITOR_SESSION -n $COMPETITOR_INPUT
	tmux send -t $COMPETITOR_SESSION:$COMPETITOR_INPUT "cd $COMPETITOR_WORKING_DIRECTORY; vim itext.txt" Enter

	tmux new-window -t $COMPETITOR_SESSION -n $COMPETITOR_RUNNER
	tmux send -t $COMPETITOR_SESSION:$COMPETITOR_RUNNER "cd $COMPETITOR_WORKING_DIRECTORY; g++ 1test.cpp -o test && ./test"
fi

tmux attach -t $COMPETITOR_SESSION:$COMPETITOR_EDITOR -c $COMPETITOR_WORKING_DIRECTORY
